package com.nhtl.notifications;

public enum NotificationEventType {
	SIGNUP_REQUESTED, SIGNUP_VALIDATED,

	PASSWORD_RESET_OTP_SENT, PASSWORD_RESET_SUCCESS,

	COMMANDE_CREATED, TRANSPORT_CREATED,

	COMMANDE_GP_ASSIGNED, TRANSPORT_GP_ASSIGNED,

	COMMANDE_STATUS_UPDATED, TRANSPORT_STATUS_UPDATED,

	COMMANDE_COMPLETED, TRANSPORT_COMPLETED
}