spring.application.name=nhtl-backend
server.port=${PORT:8080}
server.servlet.context-path=/

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jackson.time-zone=Africa/Kinshasa
spring.jackson.locale=fr_FR

# Force UTF-8 for HTTP responses and requests
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.web.resources.add-mappings=false