# =========================
# Server (DEV)
# =========================
server.port=8080

# =========================
# Database (Railway PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:59312/railway
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=XyTkYEZxRiMOHtNQWlDExRcFZddIMffM
spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Supabase (Auth only)
# =========================
supabase.project.url=https://ouswlpkxsszpxrfyvlde.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91c3dscGt4c3N6cHhyZnl2bGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMzYwMTEsImV4cCI6MjA4NjkxMjAxMX0.r43EKDGLX4iahz3cRliwBAQkV4Tgtsu80rTRGpSYP_w
supabase.jwt.secret=O+UGyUCCAD8mPw7xbRrhdRTHvbUNEoWgT8Ugm54lOcY=
supabase.service.role.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91c3dscGt4c3N6cHhyZnl2bGRlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTMzNjAxMSwiZXhwIjoyMDg2OTEyMDExfQ.ZKv8mJjbc6T1sLWNf8CW2s1emadh1BmViw89jaGwZFk

# =========================
# Mail (DEV) - providers stub via @Profile, donc rien n'est requis ici
# =========================
app.mail.from=${MAIL_FROM:no-reply@sama.local}

# =========================
# Twilio (DEV) - stub via @Profile, donc vide
# =========================
twilio.accountSid=
twilio.authToken=
twilio.fromNumber=


# Force UTF-8 for HTTP responses and requests
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.web.resources.add-mappings=false

# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.com.nhtl=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG