server.port=${PORT:8080}
server.servlet.context-path=/

# =========================
# Datasource (Railway PostgreSQL)
# =========================
# Utilise DATABASE_URL fourni par Railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.datasource.hikari.pool-prepared-statements=false
spring.datasource.hikari.prepStmtCacheSize=0
spring.datasource.hikari.prepStmtCacheSqlLimit=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =========================
# Supabase JWT/Auth
# =========================
supabase.jwt.secret=${SUPABASE_JWT_SECRET}
supabase.project.url=${SUPABASE_URL}
supabase.anon-key=${SUPABASE_ANON_KEY}

# =========================
# Mail SMTP (PROD) - Hostinger SSL (465)
# =========================
spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:465}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true

# SSL (SMTPS)
spring.mail.properties.mail.smtp.ssl.enable=true

# Sur 465 on ne fait g�n�ralement PAS du STARTTLS
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
app.mail.from=${MAIL_FROM:tech@ngom-holding.com}


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# =========================
# Twilio (PROD)
# =========================
twilio.accountSid=${TWILIO_ACCOUNT_SID:}
twilio.authToken=${TWILIO_AUTH_TOKEN:}
twilio.fromNumber=${TWILIO_FROM_NUMBER:}

# =========================
# Logging PROD
# =========================
logging.level.root=WARN
logging.level.com.nhtl=ERROR
logging.level.com.nhtl.notifications=INFO
logging.level.com.nhtl.notifications.providers=INFO
logging.level.org.springframework.mail=INFO
logging.level.org.springframework=ERROR
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.core.env=WARN
